### ISSUE TITLE
Stop scrolling until next page is loaded!

### ISSUE THREAD

**Issue by TheDeveloperYJ** [AbdulRahmanAlHamali/flutter_pagewise#10]
Hey , loved your plugin ! I have a doubt.

Suppose my pagesize is 10 items and after scrolling through 10 items I need to wait for another 10 items to load but unless they are loaded I cannot scroll . Is there any way to achieve this using pagewise .

**Comment by AbdulRahmanAlHamali** [comment]
Hello @TheDeveloperYJ , I apologize for the late answer. But due to a series of unfortunate events, I was too overwhelmed lately to follow up with the packages.

Yes, this is indeed annoying. That's why I rewrote Pagewise from scratch, and now it stops scrolling until the next page is loaded!

I will close this as fixed in version 1.0.0
