### ISSUE TITLE
Future<int> to int for totalCount

### ISSUE THREAD

**Issue by raffaelecolleo** [AbdulRahmanAlHamali/flutter_pagewise#11]
totalCount just accepts an int and I need to get this value from an external source (JSON result for a query to a DB).

This problem happens using an extended class of SearchDelegate.

`@override
  Widget buildResults(BuildContext context) {
    // TODO: implement buildResults
    return PagewiseGridView(
        pageSize: 10,
        totalCount: BackendService.getSearchTotals(query),
        crossAxisCount: 2,
        mainAxisSpacing: 10.0,
        crossAxisSpacing: 5.0,
        //childAspectRatio: 0.802,
        padding: EdgeInsets.all(5.0),
        itemBuilder: _itemBuilder,
        pageFuture: (pageIndex){
          return BackendService.getSearchItems(pageIndex, query);
        },
    );
  }`

if I change **totalCount: BackendService.getSearchTotals(query)** to **totalCount: 20 it works** but I need the exact total of Items.

How can I solve this?

**Comment by AbdulRahmanAlHamali** [comment]
Hello @raffaelecolleo , I apologize for the late answer. But due to a series of unfortunate events, I was too overwhelmed lately to follow up with the packages.

I have rewritten Pagewise, so that it does not require a `totalCount` anymore in version 1.0.0. Thus, I will close the issue as fixed in the new version.

If you prefer to use the older version. Then you could wrap the whole pagewise widget in a FutureBuilder that fetches the totalCount for you before you start displaying.
