### ISSUE TITLE
Provide full working example for the plugin And proper documentation 

### ISSUE THREAD

**Issue by asapJ** [AbdulRahmanAlHamali/flutter_pagewise#29]
Nice job On this plugin, but it will really help users get along if a full example is provided for the plugin and also if the parameter are well documented, thanks

**Comment by AbdulRahmanAlHamali** [comment]
Hello @asapJ, thank you for your feedback. I really appreciate it!

I will improve on the documentation as soon as I can. Unfortunately time hasn't been the most abundant resource recently..

Regarding the example, what is missing from the examples provided in the example directory? Maybe I can add what you're missing!

**Comment by asapJ** [comment]
The example get items from a "dummy Future" which is not so clear as it doesn't  apply to real world example and also. Probably a more realistic example where data is actually fetched from an api including value for pageSize also gotten from the api call,  should be added to the example folder,  or make a full tutorial on medium then attach the link to plugin description.

**Comment by AbdulRahmanAlHamali** [comment]
That definitely is a good idea! I'll look into it.

The problem is that I am currently low on-time, and do not have much exposure to Flutter anymore (I moved from UI development to DevOps development, completely unrelated)

I'll try to get to it in the weekend. In the meantime, if you have questions about how to use something, I would be glad to help!
