### ISSUE TITLE
home route quirk

### ISSUE THREAD

**Issue by sensiblearts** [AbdulRahmanAlHamali/flutter_pagewise#48]
Greetings,
I opened an issue earlier today but then closed it when I realized that it was a flutter isssue, not a flutter_pagewise issue.

However, this may help you:

Flutter seems to initialize the `home` route in **parallel** with the main widget initialization.

Therefore, if you happen to be using a `PagewiseListView` on your `home` route, then `PagewiseListview` will attempt to render, but finding an empty list of entries, will show only the retry button. 

```dart
 child: MaterialApp(
        home: EntriesPage(),   // problem if this widget contains a PagewiseListView
        routes: {
        //...
        }
```

So, probably what I will do is show a splash screen until data is initialized.
Hope this helps,
DA

**Comment by sjmcdowall** [comment]
Or do a Future.wait in the main before invoking the App part ..

**Comment by AbdulRahmanAlHamali** [comment]
I think the error that you were facing might be because of `_entries.sublist` that you showed in your other issue. The list is probably starting empty, and you are trying to take a sublist out of it.

I have to ask, though: why are you using Pagewise with a local list? The purpose of Pagewise is to load data from a remote server one page at a time. I suspect you might be using the tool the wrong way

**Comment by sensiblearts** [comment]
Yes, I should have written back later yesterday when I figured that out!

I am no longer using the local List _entries, and everything works smoothly and more efficiently.

Much less code, too.

Thank you for this work!

You might consider adding something to your readme, saying something like, "PageWise caches the data internally. You can simply write your  `pageFuture(pageIndex)` function to return the results of querying your local or remote database." 
DA

**Comment by AbdulRahmanAlHamali** [comment]
Cool! Yeah not a bad thing to mention. Thank you David!
