### ISSUE TITLE
pageFuture called for previous page

### ISSUE THREAD

**Issue by anderscheow** [AbdulRahmanAlHamali/flutter_pagewise#6]
I've tons of pages of data, when I scroll to page 4 or 5, then I scroll up, pageFuture for page 1 rebuild (API page 1 called)

**Comment by anderscheow** [comment]
Any update on this?

**Comment by AbdulRahmanAlHamali** [comment]
Hello @anderscheow  , I apologize for the late answer. But due to a series of unfortunate events, I was too overwhelmed lately to follow up with the packages.

I have rewritten Pagewise from scratch. The new architecture is supposed to fix many problems with the package! Can you confirm if that issue is still a problem in the new version 1.0.0?

**Comment by anderscheow** [comment]
I will try on this, thanks for the update! Keep it up!

**Comment by ariefwijaya** [comment]
Any update on this? sometime first page was duplicated but sometime doesn't, i've tried to find it but i couldn't

**Comment by AbdulRahmanAlHamali** [comment]
I see, I will look into it over the weekend and provide a fix. I think I know what might be the cause of this.

Thank you!

**Comment by AbdulRahmanAlHamali** [comment]
@Carrein do you mind sharing your code?
