### ISSUE TITLE
Scrolling Problem

### ISSUE THREAD

**Issue by raffaelecolleo** [AbdulRahmanAlHamali/flutter_pagewise#9]
Hi,
when scrolling up or down it seem that the loading are is not being blocked inside the screen.
Should n't be looking the scaffold on the next X loading items with the circular loader?

**Comment by AbdulRahmanAlHamali** [comment]
Hello @raffaelecolleo , I apologize for the late answer. But due to a series of unfortunate events, I was too overwhelmed lately to follow up with the packages.

Yes, this is indeed annoying. That's why I rewrote Pagewise from scratch, and now it stops scrolling until the next page is loaded!

I will close this as fixed in version 1.0.0
